# Generated by Django 2.1.5 on 2019-01-22 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=30)),
                ('request', models.TextField(null=True)),
                ('additional', models.TextField(null=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('permissions', models.TextField(default='{"cmds": {}, "blocks": {}, "groups": {}}')),
            ],
        ),
        migrations.CreateModel(
            name='StorageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('user', models.CharField(max_length=30, null=True)),
                ('peer', models.IntegerField(null=True)),
                ('cmd', models.CharField(max_length=30, null=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.IntegerField()),
                ('handler', models.CharField(max_length=10)),
                ('cmd', models.CharField(max_length=20)),
                ('request', models.TextField()),
                ('response', models.TextField(null=True)),
                ('traceback', models.TextField(null=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vkId', models.IntegerField(blank=True, null=True, unique=True)),
                ('tgId', models.IntegerField(blank=True, null=True, unique=True)),
                ('login', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('permissions', models.TextField(default='{"cmds": {}, "blocks": {}, "groups": {"all":{}}}')),
                ('executions', models.TextField(default='{}')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_handler.User'),
        ),
        migrations.AlterUniqueTogether(
            name='storagetable',
            unique_together={('name', 'user', 'peer', 'cmd')},
        ),
        migrations.AddField(
            model_name='errorlog',
            name='usage_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_handler.UsageLog'),
        ),
    ]
