# Generated by Django 2.2.4 on 2019-08-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0003_auto_20190303_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('accessToken', models.CharField(max_length=128, unique=True)),
                ('isBlocked', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storagetable',
            name='cmd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='storagetable',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagetable',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='storagetable',
            name='peer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='storagetable',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
