# Generated by Django 2.2.4 on 2019-08-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0004_auto_20190823_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='group_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
