# Generated by Django 2.2.4 on 2019-08-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0005_usagelog_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedgroup',
            name='confirmCode',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectedgroup',
            name='secret',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
