# Generated by Django 2.2.4 on 2019-08-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0006_auto_20190823_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedgroup',
            name='accessToken',
            field=models.CharField(max_length=128),
        ),
    ]
