# Generated by Django 2.2.4 on 2019-08-22 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0007_auto_20190823_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedgroup',
            old_name='accessToken',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='connectedgroup',
            old_name='confirmCode',
            new_name='confirm_code',
        ),
        migrations.RenameField(
            model_name='connectedgroup',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='connectedgroup',
            old_name='isBlocked',
            new_name='is_blocked',
        ),
    ]
