# Generated by Django 2.2.4 on 2019-08-22 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0008_auto_20190823_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagelog',
            old_name='group_id',
            new_name='receiver_id',
        ),
    ]
