# Generated by Django 2.2.4 on 2019-08-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0009_auto_20190823_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagelog',
            name='receiver_id',
        ),
        migrations.AddField(
            model_name='usagelog',
            name='bot_id',
            field=models.IntegerField(null=True),
        ),
    ]
