# Generated by Django 2.2.4 on 2019-08-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0010_auto_20190823_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedgroup',
            name='long_poll_url',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
