# Generated by Django 2.2.4 on 2019-08-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0012_auto_20190823_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedgroup',
            name='confirm_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='connectedgroup',
            name='secret',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
