# Generated by Django 2.2.4 on 2019-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0014_remove_connectedgroup_long_poll_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedgroup',
            name='params',
            field=models.TextField(null=True),
        ),
    ]
