# Generated by Django 2.2.4 on 2019-09-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0015_connectedgroup_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedgroup',
            name='latest_chat',
            field=models.IntegerField(null=True),
        ),
    ]
