# Generated by Django 2.2.4 on 2019-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0016_connectedgroup_latest_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedgroup',
            name='owner',
            field=models.TextField(null=True),
        ),
    ]
