# Generated by Django 2.2.4 on 2019-09-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0018_item_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases',
                                    to='bot_handler.User'),
        ),
    ]
