# Generated by Django 2.2.4 on 2019-09-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0019_auto_20190910_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys',
                                    to='bot_handler.Item'),
        ),
    ]
