# Generated by Django 2.2.4 on 2019-09-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0020_auto_20190910_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
