# Generated by Django 2.2.4 on 2019-09-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0023_auto_20190910_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_handler.User'),
        ),
    ]
