# Generated by Django 2.2.4 on 2019-09-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0024_auto_20190916_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedgroup',
            name='confirm_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='connectedgroup',
            name='latest_chat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectedgroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='bot_handler.User'),
        ),
        migrations.AlterField(
            model_name='connectedgroup',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
