# Generated by Django 2.2.4 on 2019-09-28 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0025_auto_20190928_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tgId',
            new_name='tg_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vkId',
            new_name='vk_id',
        ),
    ]
