# Generated by Django 2.2.4 on 2019-09-29 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0026_auto_20190928_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagelog',
            old_name='handler',
            new_name='messenger',
        ),
    ]
