# Generated by Django 2.2.4 on 2019-09-29 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot_handler', '0027_auto_20190929_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='type',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='errorlog',
            old_name='handler',
            new_name='messenger',
        ),
        migrations.RenameField(
            model_name='usagelog',
            old_name='comment',
            new_name='comments',
        ),
    ]
