# Generated by Django 2.1.5 on 2019-01-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(max_length=100)),
                ('latest_chat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_my', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('bots_data', models.TextField()),
                ('antikick', models.BooleanField(default=False)),
            ],
        ),
    ]
